keys:
  - &earn-zeus age1ea4hdecw9hw6ae9728paskysc6hrwxs9tx5j22hmyuz5hktar3cqy0zrga
  - &earn age1vhd283gt45vjd69trftmakc0e8e9kff73l30p26atc6e77rn54qq44e65u
  - &host_nixwork age10p3hl574ycr9ps40lkfhp79w5d2xkemnez9e95j64nrwhs4wguasvav6zx
  - &nixwork age1gc3aspyynscgql7zgaed33h54ut6ftkazy56h8hrhej5a0xhws8smt9u2g

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *earn-zeus
          - *earn
          - *host_nixwork
          - *nixwork
