keys:
  - &earn-zeus age1ea4hdecw9hw6ae9728paskysc6hrwxs9tx5j22hmyuz5hktar3cqy0zrga
  - &earn age1vhd283gt45vjd69trftmakc0e8e9kff73l30p26atc6e77rn54qq44e65u
  - &nixwork age10p3hl574ycr9ps40lkfhp79w5d2xkemnez9e95j64nrwhs4wguasvav6zx

creation_rules:
  - path_regex: secrets/secrets\.yaml$
    key_groups:
      - age:
          - *earn-zeus
          - *earn
          - *nixwork
