# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-96e5043e-e9eb-47ec-be68-4234a9e4fd1f";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-96e5043e-e9eb-47ec-be68-4234a9e4fd1f".device = "/dev/disk/by-uuid/96e5043e-e9eb-47ec-be68-4234a9e4fd1f";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8A34-2982";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-dace8e36-8066-4406-b113-a93b047bf55d"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
