{ ... }: {
  flake.nixosModules.nixworkHardware =
    # Do not modify this file!  It was generated by ‘nixos-generate-config’
    # and may be overwritten by future invocations.  Please make changes
    # to /etc/nixos/configuration.nix instead.
    {
      config,
      lib,
      modulesPath,
      ...
    }:

    {
      imports = [
        (modulesPath + "/installer/scan/not-detected.nix")
      ];

      boot.initrd.availableKernelModules = [
        "nvme"
        "xhci_pci"
        "thunderbolt"
        "usb_storage"
        "sd_mod"
      ];
      boot.initrd.kernelModules = [ ];
      boot.kernelModules = [ "kvm-amd" ];
      boot.extraModulePackages = [ ];

      fileSystems."/" = {
        device = "/dev/mapper/luks-0fa62455-6ff8-49f4-a4d9-12c4470d2c7f";
        fsType = "ext4";
      };

      boot.initrd.luks.devices."luks-0fa62455-6ff8-49f4-a4d9-12c4470d2c7f".device =
        "/dev/disk/by-uuid/0fa62455-6ff8-49f4-a4d9-12c4470d2c7f";

      fileSystems."/boot" = {
        device = "/dev/disk/by-uuid/7A83-A912";
        fsType = "vfat";
        options = [
          "fmask=0077"
          "dmask=0077"
        ];
      };

      swapDevices = [
        { device = "/dev/mapper/luks-e23c56ef-712d-4c70-9b40-525e09217a72"; }
      ];

      nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
      hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
    };
}
