# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-1c6c84bd-804e-4531-b5cb-191c92f33282";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-1c6c84bd-804e-4531-b5cb-191c92f33282".device = "/dev/disk/by-uuid/1c6c84bd-804e-4531-b5cb-191c92f33282";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/56A8-4275";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-59f0c2b6-2617-42dc-884a-35acdd0c44c6"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
